name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  forge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: oven-sh/setup-bun@v2
      - uses: foundry-rs/foundry-toolchain@v1
      - run: bun install --frozen-lockfile
      - run: forge build --sizes
      - run: forge test -vvv
        env:
          FOUNDRY_PROFILE: ci
